### PR TITLE
Added map to Search Map Screen

### PR DESCRIPTION
**Pull request by clinturbin**
For this branch, I added some components to display the map on the Search Map Screen. Currently, all the files are in the src directory. For organizational purposes, I was thinking we could maybe put all the map component files in their own folder within the src directory. Let me me know what you think.

@running-on-sunshine: Could you please review?

### CODE REVIEW

**Comment by running-on-sunshine** [comment]
Thoughts:

- Yes! to moving all of the map components into their own folder within the src directory. Really like this idea! It's definitely going to help with organizing our components moving forward! 
- This is an awesome start! Very excited to have the map rendered onto the screen. Great work, @clinturbin! 🙂

You may definitely proceed to merge when you are ready! 👍

**Review by running-on-sunshine — APPROVED** [review]

**Comment by clinturbin** [comment]
I just modified the file structure based on what we discussed.

@running-on-sunshine: Could you please review?

**Comment by clinturbin** [comment]
I moved map-styling.css to the stylesheets folder.

**Comment by running-on-sunshine** [comment]
This looks great! Thank you for incorporating the suggested changes! I really appreciate that! 🙂

These changes look ready to be merged! 👍

**Pull request merged**
